addons:
  apt:
    sources:
      - debian-sid
    packages:
      - gcc-arm-none-eabi
sudo: false
script: cd firmware/nordic_nrf51/app/ble_peripheral/ledbrick_pwm/pca10028/s110/armgcc && make
language: c
